//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ZeroModel", "FK_Calculations_IpAddresses", "IpAddresses", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ProductZero.Data.IpAddresses), "Calculations", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProductZero.Data.Calculations), true)]
[assembly: EdmRelationshipAttribute("ZeroModel", "FK_NormalizedCalculations_Calculations", "Calculations", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ProductZero.Data.Calculations), "NormalizedCalculations", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ProductZero.Data.NormalizedCalculations), true)]
[assembly: EdmRelationshipAttribute("ZeroModel", "FK_NormalizedCalculations_IpAddresses", "IpAddresses", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ProductZero.Data.IpAddresses), "NormalizedCalculations", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProductZero.Data.NormalizedCalculations), true)]

#endregion

namespace ProductZero.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ZeroEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ZeroEntities object using the connection string found in the 'ZeroEntities' section of the application configuration file.
        /// </summary>
        public ZeroEntities() : base("name=ZeroEntities", "ZeroEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ZeroEntities object.
        /// </summary>
        public ZeroEntities(string connectionString) : base(connectionString, "ZeroEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ZeroEntities object.
        /// </summary>
        public ZeroEntities(EntityConnection connection) : base(connection, "ZeroEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<IpAddresses> IpAddresses
        {
            get
            {
                if ((_IpAddresses == null))
                {
                    _IpAddresses = base.CreateObjectSet<IpAddresses>("IpAddresses");
                }
                return _IpAddresses;
            }
        }
        private ObjectSet<IpAddresses> _IpAddresses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Calculations> Calculations
        {
            get
            {
                if ((_Calculations == null))
                {
                    _Calculations = base.CreateObjectSet<Calculations>("Calculations");
                }
                return _Calculations;
            }
        }
        private ObjectSet<Calculations> _Calculations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NormalizedCalculations> NormalizedCalculations
        {
            get
            {
                if ((_NormalizedCalculations == null))
                {
                    _NormalizedCalculations = base.CreateObjectSet<NormalizedCalculations>("NormalizedCalculations");
                }
                return _NormalizedCalculations;
            }
        }
        private ObjectSet<NormalizedCalculations> _NormalizedCalculations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OnSiteEngagements> OnSiteEngagements
        {
            get
            {
                if ((_OnSiteEngagements == null))
                {
                    _OnSiteEngagements = base.CreateObjectSet<OnSiteEngagements>("OnSiteEngagements");
                }
                return _OnSiteEngagements;
            }
        }
        private ObjectSet<OnSiteEngagements> _OnSiteEngagements;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the IpAddresses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIpAddresses(IpAddresses ipAddresses)
        {
            base.AddObject("IpAddresses", ipAddresses);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Calculations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCalculations(Calculations calculations)
        {
            base.AddObject("Calculations", calculations);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NormalizedCalculations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNormalizedCalculations(NormalizedCalculations normalizedCalculations)
        {
            base.AddObject("NormalizedCalculations", normalizedCalculations);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OnSiteEngagements EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOnSiteEngagements(OnSiteEngagements onSiteEngagements)
        {
            base.AddObject("OnSiteEngagements", onSiteEngagements);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ZeroModel", Name="Calculations")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Calculations : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Calculations object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="currency">Initial value of the Currency property.</param>
        /// <param name="totalCosts">Initial value of the TotalCosts property.</param>
        /// <param name="addressId">Initial value of the AddressId property.</param>
        /// <param name="timestamp">Initial value of the Timestamp property.</param>
        /// <param name="projectSize">Initial value of the ProjectSize property.</param>
        /// <param name="quality">Initial value of the Quality property.</param>
        /// <param name="surplusPercent">Initial value of the SurplusPercent property.</param>
        /// <param name="surplusInvestment">Initial value of the SurplusInvestment property.</param>
        /// <param name="devCosts">Initial value of the DevCosts property.</param>
        /// <param name="modDevCosts">Initial value of the ModDevCosts property.</param>
        /// <param name="maintCosts">Initial value of the MaintCosts property.</param>
        /// <param name="modMaintCosts">Initial value of the ModMaintCosts property.</param>
        /// <param name="modTotalCosts">Initial value of the ModTotalCosts property.</param>
        /// <param name="maintPercent">Initial value of the MaintPercent property.</param>
        /// <param name="modMaintPercent">Initial value of the ModMaintPercent property.</param>
        /// <param name="lifetime">Initial value of the Lifetime property.</param>
        /// <param name="breakEven">Initial value of the BreakEven property.</param>
        /// <param name="roi">Initial value of the Roi property.</param>
        /// <param name="avgYearlySaving">Initial value of the AvgYearlySaving property.</param>
        /// <param name="maxYearlySaving">Initial value of the MaxYearlySaving property.</param>
        /// <param name="minYearlySaving">Initial value of the MinYearlySaving property.</param>
        /// <param name="staffCostsPerYear">Initial value of the StaffCostsPerYear property.</param>
        public static Calculations CreateCalculations(global::System.Guid id, global::System.String currency, global::System.Int64 totalCosts, global::System.Guid addressId, global::System.DateTime timestamp, global::System.Int32 projectSize, global::System.Int32 quality, global::System.Int32 surplusPercent, global::System.Int64 surplusInvestment, global::System.Int64 devCosts, global::System.Int64 modDevCosts, global::System.Int64 maintCosts, global::System.Int64 modMaintCosts, global::System.Int64 modTotalCosts, global::System.Int32 maintPercent, global::System.Int32 modMaintPercent, global::System.Int32 lifetime, global::System.Double breakEven, global::System.Double roi, global::System.Int64 avgYearlySaving, global::System.Int64 maxYearlySaving, global::System.Int64 minYearlySaving, global::System.Int64 staffCostsPerYear)
        {
            Calculations calculations = new Calculations();
            calculations.Id = id;
            calculations.Currency = currency;
            calculations.TotalCosts = totalCosts;
            calculations.AddressId = addressId;
            calculations.Timestamp = timestamp;
            calculations.ProjectSize = projectSize;
            calculations.Quality = quality;
            calculations.SurplusPercent = surplusPercent;
            calculations.SurplusInvestment = surplusInvestment;
            calculations.DevCosts = devCosts;
            calculations.ModDevCosts = modDevCosts;
            calculations.MaintCosts = maintCosts;
            calculations.ModMaintCosts = modMaintCosts;
            calculations.ModTotalCosts = modTotalCosts;
            calculations.MaintPercent = maintPercent;
            calculations.ModMaintPercent = modMaintPercent;
            calculations.Lifetime = lifetime;
            calculations.BreakEven = breakEven;
            calculations.Roi = roi;
            calculations.AvgYearlySaving = avgYearlySaving;
            calculations.MaxYearlySaving = maxYearlySaving;
            calculations.MinYearlySaving = minYearlySaving;
            calculations.StaffCostsPerYear = staffCostsPerYear;
            return calculations;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Currency
        {
            get
            {
                return _Currency;
            }
            set
            {
                OnCurrencyChanging(value);
                ReportPropertyChanging("Currency");
                _Currency = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Currency");
                OnCurrencyChanged();
            }
        }
        private global::System.String _Currency;
        partial void OnCurrencyChanging(global::System.String value);
        partial void OnCurrencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TotalCosts
        {
            get
            {
                return _TotalCosts;
            }
            set
            {
                OnTotalCostsChanging(value);
                ReportPropertyChanging("TotalCosts");
                _TotalCosts = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalCosts");
                OnTotalCostsChanged();
            }
        }
        private global::System.Int64 _TotalCosts;
        partial void OnTotalCostsChanging(global::System.Int64 value);
        partial void OnTotalCostsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid AddressId
        {
            get
            {
                return _AddressId;
            }
            set
            {
                OnAddressIdChanging(value);
                ReportPropertyChanging("AddressId");
                _AddressId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddressId");
                OnAddressIdChanged();
            }
        }
        private global::System.Guid _AddressId;
        partial void OnAddressIdChanging(global::System.Guid value);
        partial void OnAddressIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Timestamp
        {
            get
            {
                return _Timestamp;
            }
            set
            {
                OnTimestampChanging(value);
                ReportPropertyChanging("Timestamp");
                _Timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Timestamp");
                OnTimestampChanged();
            }
        }
        private global::System.DateTime _Timestamp;
        partial void OnTimestampChanging(global::System.DateTime value);
        partial void OnTimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProjectSize
        {
            get
            {
                return _ProjectSize;
            }
            set
            {
                OnProjectSizeChanging(value);
                ReportPropertyChanging("ProjectSize");
                _ProjectSize = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProjectSize");
                OnProjectSizeChanged();
            }
        }
        private global::System.Int32 _ProjectSize;
        partial void OnProjectSizeChanging(global::System.Int32 value);
        partial void OnProjectSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Quality
        {
            get
            {
                return _Quality;
            }
            set
            {
                OnQualityChanging(value);
                ReportPropertyChanging("Quality");
                _Quality = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quality");
                OnQualityChanged();
            }
        }
        private global::System.Int32 _Quality;
        partial void OnQualityChanging(global::System.Int32 value);
        partial void OnQualityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SurplusPercent
        {
            get
            {
                return _SurplusPercent;
            }
            set
            {
                OnSurplusPercentChanging(value);
                ReportPropertyChanging("SurplusPercent");
                _SurplusPercent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SurplusPercent");
                OnSurplusPercentChanged();
            }
        }
        private global::System.Int32 _SurplusPercent;
        partial void OnSurplusPercentChanging(global::System.Int32 value);
        partial void OnSurplusPercentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 SurplusInvestment
        {
            get
            {
                return _SurplusInvestment;
            }
            set
            {
                OnSurplusInvestmentChanging(value);
                ReportPropertyChanging("SurplusInvestment");
                _SurplusInvestment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SurplusInvestment");
                OnSurplusInvestmentChanged();
            }
        }
        private global::System.Int64 _SurplusInvestment;
        partial void OnSurplusInvestmentChanging(global::System.Int64 value);
        partial void OnSurplusInvestmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 DevCosts
        {
            get
            {
                return _DevCosts;
            }
            set
            {
                OnDevCostsChanging(value);
                ReportPropertyChanging("DevCosts");
                _DevCosts = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DevCosts");
                OnDevCostsChanged();
            }
        }
        private global::System.Int64 _DevCosts;
        partial void OnDevCostsChanging(global::System.Int64 value);
        partial void OnDevCostsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ModDevCosts
        {
            get
            {
                return _ModDevCosts;
            }
            set
            {
                OnModDevCostsChanging(value);
                ReportPropertyChanging("ModDevCosts");
                _ModDevCosts = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModDevCosts");
                OnModDevCostsChanged();
            }
        }
        private global::System.Int64 _ModDevCosts;
        partial void OnModDevCostsChanging(global::System.Int64 value);
        partial void OnModDevCostsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MaintCosts
        {
            get
            {
                return _MaintCosts;
            }
            set
            {
                OnMaintCostsChanging(value);
                ReportPropertyChanging("MaintCosts");
                _MaintCosts = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaintCosts");
                OnMaintCostsChanged();
            }
        }
        private global::System.Int64 _MaintCosts;
        partial void OnMaintCostsChanging(global::System.Int64 value);
        partial void OnMaintCostsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ModMaintCosts
        {
            get
            {
                return _ModMaintCosts;
            }
            set
            {
                OnModMaintCostsChanging(value);
                ReportPropertyChanging("ModMaintCosts");
                _ModMaintCosts = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModMaintCosts");
                OnModMaintCostsChanged();
            }
        }
        private global::System.Int64 _ModMaintCosts;
        partial void OnModMaintCostsChanging(global::System.Int64 value);
        partial void OnModMaintCostsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ModTotalCosts
        {
            get
            {
                return _ModTotalCosts;
            }
            set
            {
                OnModTotalCostsChanging(value);
                ReportPropertyChanging("ModTotalCosts");
                _ModTotalCosts = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModTotalCosts");
                OnModTotalCostsChanged();
            }
        }
        private global::System.Int64 _ModTotalCosts;
        partial void OnModTotalCostsChanging(global::System.Int64 value);
        partial void OnModTotalCostsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaintPercent
        {
            get
            {
                return _MaintPercent;
            }
            set
            {
                OnMaintPercentChanging(value);
                ReportPropertyChanging("MaintPercent");
                _MaintPercent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaintPercent");
                OnMaintPercentChanged();
            }
        }
        private global::System.Int32 _MaintPercent;
        partial void OnMaintPercentChanging(global::System.Int32 value);
        partial void OnMaintPercentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModMaintPercent
        {
            get
            {
                return _ModMaintPercent;
            }
            set
            {
                OnModMaintPercentChanging(value);
                ReportPropertyChanging("ModMaintPercent");
                _ModMaintPercent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModMaintPercent");
                OnModMaintPercentChanged();
            }
        }
        private global::System.Int32 _ModMaintPercent;
        partial void OnModMaintPercentChanging(global::System.Int32 value);
        partial void OnModMaintPercentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Lifetime
        {
            get
            {
                return _Lifetime;
            }
            set
            {
                OnLifetimeChanging(value);
                ReportPropertyChanging("Lifetime");
                _Lifetime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Lifetime");
                OnLifetimeChanged();
            }
        }
        private global::System.Int32 _Lifetime;
        partial void OnLifetimeChanging(global::System.Int32 value);
        partial void OnLifetimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double BreakEven
        {
            get
            {
                return _BreakEven;
            }
            set
            {
                OnBreakEvenChanging(value);
                ReportPropertyChanging("BreakEven");
                _BreakEven = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BreakEven");
                OnBreakEvenChanged();
            }
        }
        private global::System.Double _BreakEven;
        partial void OnBreakEvenChanging(global::System.Double value);
        partial void OnBreakEvenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Roi
        {
            get
            {
                return _Roi;
            }
            set
            {
                OnRoiChanging(value);
                ReportPropertyChanging("Roi");
                _Roi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Roi");
                OnRoiChanged();
            }
        }
        private global::System.Double _Roi;
        partial void OnRoiChanging(global::System.Double value);
        partial void OnRoiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AvgYearlySaving
        {
            get
            {
                return _AvgYearlySaving;
            }
            set
            {
                OnAvgYearlySavingChanging(value);
                ReportPropertyChanging("AvgYearlySaving");
                _AvgYearlySaving = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AvgYearlySaving");
                OnAvgYearlySavingChanged();
            }
        }
        private global::System.Int64 _AvgYearlySaving;
        partial void OnAvgYearlySavingChanging(global::System.Int64 value);
        partial void OnAvgYearlySavingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MaxYearlySaving
        {
            get
            {
                return _MaxYearlySaving;
            }
            set
            {
                OnMaxYearlySavingChanging(value);
                ReportPropertyChanging("MaxYearlySaving");
                _MaxYearlySaving = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxYearlySaving");
                OnMaxYearlySavingChanged();
            }
        }
        private global::System.Int64 _MaxYearlySaving;
        partial void OnMaxYearlySavingChanging(global::System.Int64 value);
        partial void OnMaxYearlySavingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MinYearlySaving
        {
            get
            {
                return _MinYearlySaving;
            }
            set
            {
                OnMinYearlySavingChanging(value);
                ReportPropertyChanging("MinYearlySaving");
                _MinYearlySaving = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinYearlySaving");
                OnMinYearlySavingChanged();
            }
        }
        private global::System.Int64 _MinYearlySaving;
        partial void OnMinYearlySavingChanging(global::System.Int64 value);
        partial void OnMinYearlySavingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 StaffCostsPerYear
        {
            get
            {
                return _StaffCostsPerYear;
            }
            set
            {
                OnStaffCostsPerYearChanging(value);
                ReportPropertyChanging("StaffCostsPerYear");
                _StaffCostsPerYear = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StaffCostsPerYear");
                OnStaffCostsPerYearChanged();
            }
        }
        private global::System.Int64 _StaffCostsPerYear;
        partial void OnStaffCostsPerYearChanging(global::System.Int64 value);
        partial void OnStaffCostsPerYearChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ZeroModel", "FK_Calculations_IpAddresses", "IpAddresses")]
        public IpAddresses IpAddress
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<IpAddresses>("ZeroModel.FK_Calculations_IpAddresses", "IpAddresses").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<IpAddresses>("ZeroModel.FK_Calculations_IpAddresses", "IpAddresses").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<IpAddresses> IpAddressReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<IpAddresses>("ZeroModel.FK_Calculations_IpAddresses", "IpAddresses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<IpAddresses>("ZeroModel.FK_Calculations_IpAddresses", "IpAddresses", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ZeroModel", "FK_NormalizedCalculations_Calculations", "NormalizedCalculations")]
        public NormalizedCalculations NormalizedCalculation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NormalizedCalculations>("ZeroModel.FK_NormalizedCalculations_Calculations", "NormalizedCalculations").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NormalizedCalculations>("ZeroModel.FK_NormalizedCalculations_Calculations", "NormalizedCalculations").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NormalizedCalculations> NormalizedCalculationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NormalizedCalculations>("ZeroModel.FK_NormalizedCalculations_Calculations", "NormalizedCalculations");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NormalizedCalculations>("ZeroModel.FK_NormalizedCalculations_Calculations", "NormalizedCalculations", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ZeroModel", Name="IpAddresses")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class IpAddresses : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new IpAddresses object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        public static IpAddresses CreateIpAddresses(global::System.Guid id, global::System.String address)
        {
            IpAddresses ipAddresses = new IpAddresses();
            ipAddresses.Id = id;
            ipAddresses.Address = address;
            return ipAddresses;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ZeroModel", "FK_Calculations_IpAddresses", "Calculations")]
        public EntityCollection<Calculations> Calculations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Calculations>("ZeroModel.FK_Calculations_IpAddresses", "Calculations");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Calculations>("ZeroModel.FK_Calculations_IpAddresses", "Calculations", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ZeroModel", "FK_NormalizedCalculations_IpAddresses", "NormalizedCalculations")]
        public EntityCollection<NormalizedCalculations> NormalizedCalculations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<NormalizedCalculations>("ZeroModel.FK_NormalizedCalculations_IpAddresses", "NormalizedCalculations");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<NormalizedCalculations>("ZeroModel.FK_NormalizedCalculations_IpAddresses", "NormalizedCalculations", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ZeroModel", Name="NormalizedCalculations")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NormalizedCalculations : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NormalizedCalculations object.
        /// </summary>
        /// <param name="calculationId">Initial value of the CalculationId property.</param>
        /// <param name="timestamp">Initial value of the Timestamp property.</param>
        /// <param name="totalCosts">Initial value of the TotalCosts property.</param>
        /// <param name="srcCurrency">Initial value of the SrcCurrency property.</param>
        /// <param name="currency">Initial value of the Currency property.</param>
        /// <param name="projectSize">Initial value of the ProjectSize property.</param>
        /// <param name="lifeTime">Initial value of the LifeTime property.</param>
        /// <param name="quality">Initial value of the Quality property.</param>
        /// <param name="surplusPercent">Initial value of the SurplusPercent property.</param>
        /// <param name="surplusInvestment">Initial value of the SurplusInvestment property.</param>
        /// <param name="devCosts">Initial value of the DevCosts property.</param>
        /// <param name="modDevCosts">Initial value of the ModDevCosts property.</param>
        /// <param name="maintCosts">Initial value of the MaintCosts property.</param>
        /// <param name="modMaintCosts">Initial value of the ModMaintCosts property.</param>
        /// <param name="modTotalCosts">Initial value of the ModTotalCosts property.</param>
        /// <param name="maintPercent">Initial value of the MaintPercent property.</param>
        /// <param name="modMaintPercent">Initial value of the ModMaintPercent property.</param>
        /// <param name="breakEven">Initial value of the BreakEven property.</param>
        /// <param name="roi">Initial value of the Roi property.</param>
        /// <param name="avgYearlySaving">Initial value of the AvgYearlySaving property.</param>
        /// <param name="maxYearlySaving">Initial value of the MaxYearlySaving property.</param>
        /// <param name="minYearlySaving">Initial value of the MinYearlySaving property.</param>
        /// <param name="staffCostsPerYear">Initial value of the StaffCostsPerYear property.</param>
        public static NormalizedCalculations CreateNormalizedCalculations(global::System.Guid calculationId, global::System.DateTime timestamp, global::System.Double totalCosts, global::System.String srcCurrency, global::System.String currency, global::System.Int32 projectSize, global::System.Int32 lifeTime, global::System.Int32 quality, global::System.Int32 surplusPercent, global::System.Double surplusInvestment, global::System.Double devCosts, global::System.Double modDevCosts, global::System.Double maintCosts, global::System.Double modMaintCosts, global::System.Double modTotalCosts, global::System.Double maintPercent, global::System.Double modMaintPercent, global::System.Double breakEven, global::System.Double roi, global::System.Double avgYearlySaving, global::System.Double maxYearlySaving, global::System.Double minYearlySaving, global::System.Double staffCostsPerYear)
        {
            NormalizedCalculations normalizedCalculations = new NormalizedCalculations();
            normalizedCalculations.CalculationId = calculationId;
            normalizedCalculations.Timestamp = timestamp;
            normalizedCalculations.TotalCosts = totalCosts;
            normalizedCalculations.SrcCurrency = srcCurrency;
            normalizedCalculations.Currency = currency;
            normalizedCalculations.ProjectSize = projectSize;
            normalizedCalculations.LifeTime = lifeTime;
            normalizedCalculations.Quality = quality;
            normalizedCalculations.SurplusPercent = surplusPercent;
            normalizedCalculations.SurplusInvestment = surplusInvestment;
            normalizedCalculations.DevCosts = devCosts;
            normalizedCalculations.ModDevCosts = modDevCosts;
            normalizedCalculations.MaintCosts = maintCosts;
            normalizedCalculations.ModMaintCosts = modMaintCosts;
            normalizedCalculations.ModTotalCosts = modTotalCosts;
            normalizedCalculations.MaintPercent = maintPercent;
            normalizedCalculations.ModMaintPercent = modMaintPercent;
            normalizedCalculations.BreakEven = breakEven;
            normalizedCalculations.Roi = roi;
            normalizedCalculations.AvgYearlySaving = avgYearlySaving;
            normalizedCalculations.MaxYearlySaving = maxYearlySaving;
            normalizedCalculations.MinYearlySaving = minYearlySaving;
            normalizedCalculations.StaffCostsPerYear = staffCostsPerYear;
            return normalizedCalculations;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CalculationId
        {
            get
            {
                return _CalculationId;
            }
            set
            {
                if (_CalculationId != value)
                {
                    OnCalculationIdChanging(value);
                    ReportPropertyChanging("CalculationId");
                    _CalculationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CalculationId");
                    OnCalculationIdChanged();
                }
            }
        }
        private global::System.Guid _CalculationId;
        partial void OnCalculationIdChanging(global::System.Guid value);
        partial void OnCalculationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Timestamp
        {
            get
            {
                return _Timestamp;
            }
            set
            {
                OnTimestampChanging(value);
                ReportPropertyChanging("Timestamp");
                _Timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Timestamp");
                OnTimestampChanged();
            }
        }
        private global::System.DateTime _Timestamp;
        partial void OnTimestampChanging(global::System.DateTime value);
        partial void OnTimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double TotalCosts
        {
            get
            {
                return _TotalCosts;
            }
            set
            {
                OnTotalCostsChanging(value);
                ReportPropertyChanging("TotalCosts");
                _TotalCosts = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalCosts");
                OnTotalCostsChanged();
            }
        }
        private global::System.Double _TotalCosts;
        partial void OnTotalCostsChanging(global::System.Double value);
        partial void OnTotalCostsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SrcCurrency
        {
            get
            {
                return _SrcCurrency;
            }
            set
            {
                OnSrcCurrencyChanging(value);
                ReportPropertyChanging("SrcCurrency");
                _SrcCurrency = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SrcCurrency");
                OnSrcCurrencyChanged();
            }
        }
        private global::System.String _SrcCurrency;
        partial void OnSrcCurrencyChanging(global::System.String value);
        partial void OnSrcCurrencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Currency
        {
            get
            {
                return _Currency;
            }
            set
            {
                OnCurrencyChanging(value);
                ReportPropertyChanging("Currency");
                _Currency = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Currency");
                OnCurrencyChanged();
            }
        }
        private global::System.String _Currency;
        partial void OnCurrencyChanging(global::System.String value);
        partial void OnCurrencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProjectSize
        {
            get
            {
                return _ProjectSize;
            }
            set
            {
                OnProjectSizeChanging(value);
                ReportPropertyChanging("ProjectSize");
                _ProjectSize = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProjectSize");
                OnProjectSizeChanged();
            }
        }
        private global::System.Int32 _ProjectSize;
        partial void OnProjectSizeChanging(global::System.Int32 value);
        partial void OnProjectSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LifeTime
        {
            get
            {
                return _LifeTime;
            }
            set
            {
                OnLifeTimeChanging(value);
                ReportPropertyChanging("LifeTime");
                _LifeTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LifeTime");
                OnLifeTimeChanged();
            }
        }
        private global::System.Int32 _LifeTime;
        partial void OnLifeTimeChanging(global::System.Int32 value);
        partial void OnLifeTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Quality
        {
            get
            {
                return _Quality;
            }
            set
            {
                OnQualityChanging(value);
                ReportPropertyChanging("Quality");
                _Quality = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quality");
                OnQualityChanged();
            }
        }
        private global::System.Int32 _Quality;
        partial void OnQualityChanging(global::System.Int32 value);
        partial void OnQualityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SurplusPercent
        {
            get
            {
                return _SurplusPercent;
            }
            set
            {
                OnSurplusPercentChanging(value);
                ReportPropertyChanging("SurplusPercent");
                _SurplusPercent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SurplusPercent");
                OnSurplusPercentChanged();
            }
        }
        private global::System.Int32 _SurplusPercent;
        partial void OnSurplusPercentChanging(global::System.Int32 value);
        partial void OnSurplusPercentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double SurplusInvestment
        {
            get
            {
                return _SurplusInvestment;
            }
            set
            {
                OnSurplusInvestmentChanging(value);
                ReportPropertyChanging("SurplusInvestment");
                _SurplusInvestment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SurplusInvestment");
                OnSurplusInvestmentChanged();
            }
        }
        private global::System.Double _SurplusInvestment;
        partial void OnSurplusInvestmentChanging(global::System.Double value);
        partial void OnSurplusInvestmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double DevCosts
        {
            get
            {
                return _DevCosts;
            }
            set
            {
                OnDevCostsChanging(value);
                ReportPropertyChanging("DevCosts");
                _DevCosts = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DevCosts");
                OnDevCostsChanged();
            }
        }
        private global::System.Double _DevCosts;
        partial void OnDevCostsChanging(global::System.Double value);
        partial void OnDevCostsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double ModDevCosts
        {
            get
            {
                return _ModDevCosts;
            }
            set
            {
                OnModDevCostsChanging(value);
                ReportPropertyChanging("ModDevCosts");
                _ModDevCosts = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModDevCosts");
                OnModDevCostsChanged();
            }
        }
        private global::System.Double _ModDevCosts;
        partial void OnModDevCostsChanging(global::System.Double value);
        partial void OnModDevCostsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double MaintCosts
        {
            get
            {
                return _MaintCosts;
            }
            set
            {
                OnMaintCostsChanging(value);
                ReportPropertyChanging("MaintCosts");
                _MaintCosts = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaintCosts");
                OnMaintCostsChanged();
            }
        }
        private global::System.Double _MaintCosts;
        partial void OnMaintCostsChanging(global::System.Double value);
        partial void OnMaintCostsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double ModMaintCosts
        {
            get
            {
                return _ModMaintCosts;
            }
            set
            {
                OnModMaintCostsChanging(value);
                ReportPropertyChanging("ModMaintCosts");
                _ModMaintCosts = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModMaintCosts");
                OnModMaintCostsChanged();
            }
        }
        private global::System.Double _ModMaintCosts;
        partial void OnModMaintCostsChanging(global::System.Double value);
        partial void OnModMaintCostsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double ModTotalCosts
        {
            get
            {
                return _ModTotalCosts;
            }
            set
            {
                OnModTotalCostsChanging(value);
                ReportPropertyChanging("ModTotalCosts");
                _ModTotalCosts = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModTotalCosts");
                OnModTotalCostsChanged();
            }
        }
        private global::System.Double _ModTotalCosts;
        partial void OnModTotalCostsChanging(global::System.Double value);
        partial void OnModTotalCostsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double MaintPercent
        {
            get
            {
                return _MaintPercent;
            }
            set
            {
                OnMaintPercentChanging(value);
                ReportPropertyChanging("MaintPercent");
                _MaintPercent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaintPercent");
                OnMaintPercentChanged();
            }
        }
        private global::System.Double _MaintPercent;
        partial void OnMaintPercentChanging(global::System.Double value);
        partial void OnMaintPercentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double ModMaintPercent
        {
            get
            {
                return _ModMaintPercent;
            }
            set
            {
                OnModMaintPercentChanging(value);
                ReportPropertyChanging("ModMaintPercent");
                _ModMaintPercent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModMaintPercent");
                OnModMaintPercentChanged();
            }
        }
        private global::System.Double _ModMaintPercent;
        partial void OnModMaintPercentChanging(global::System.Double value);
        partial void OnModMaintPercentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double BreakEven
        {
            get
            {
                return _BreakEven;
            }
            set
            {
                OnBreakEvenChanging(value);
                ReportPropertyChanging("BreakEven");
                _BreakEven = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BreakEven");
                OnBreakEvenChanged();
            }
        }
        private global::System.Double _BreakEven;
        partial void OnBreakEvenChanging(global::System.Double value);
        partial void OnBreakEvenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Roi
        {
            get
            {
                return _Roi;
            }
            set
            {
                OnRoiChanging(value);
                ReportPropertyChanging("Roi");
                _Roi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Roi");
                OnRoiChanged();
            }
        }
        private global::System.Double _Roi;
        partial void OnRoiChanging(global::System.Double value);
        partial void OnRoiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double AvgYearlySaving
        {
            get
            {
                return _AvgYearlySaving;
            }
            set
            {
                OnAvgYearlySavingChanging(value);
                ReportPropertyChanging("AvgYearlySaving");
                _AvgYearlySaving = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AvgYearlySaving");
                OnAvgYearlySavingChanged();
            }
        }
        private global::System.Double _AvgYearlySaving;
        partial void OnAvgYearlySavingChanging(global::System.Double value);
        partial void OnAvgYearlySavingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double MaxYearlySaving
        {
            get
            {
                return _MaxYearlySaving;
            }
            set
            {
                OnMaxYearlySavingChanging(value);
                ReportPropertyChanging("MaxYearlySaving");
                _MaxYearlySaving = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxYearlySaving");
                OnMaxYearlySavingChanged();
            }
        }
        private global::System.Double _MaxYearlySaving;
        partial void OnMaxYearlySavingChanging(global::System.Double value);
        partial void OnMaxYearlySavingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double MinYearlySaving
        {
            get
            {
                return _MinYearlySaving;
            }
            set
            {
                OnMinYearlySavingChanging(value);
                ReportPropertyChanging("MinYearlySaving");
                _MinYearlySaving = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinYearlySaving");
                OnMinYearlySavingChanged();
            }
        }
        private global::System.Double _MinYearlySaving;
        partial void OnMinYearlySavingChanging(global::System.Double value);
        partial void OnMinYearlySavingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> AddressId
        {
            get
            {
                return _AddressId;
            }
            set
            {
                OnAddressIdChanging(value);
                ReportPropertyChanging("AddressId");
                _AddressId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddressId");
                OnAddressIdChanged();
            }
        }
        private Nullable<global::System.Guid> _AddressId;
        partial void OnAddressIdChanging(Nullable<global::System.Guid> value);
        partial void OnAddressIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double StaffCostsPerYear
        {
            get
            {
                return _StaffCostsPerYear;
            }
            set
            {
                OnStaffCostsPerYearChanging(value);
                ReportPropertyChanging("StaffCostsPerYear");
                _StaffCostsPerYear = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StaffCostsPerYear");
                OnStaffCostsPerYearChanged();
            }
        }
        private global::System.Double _StaffCostsPerYear;
        partial void OnStaffCostsPerYearChanging(global::System.Double value);
        partial void OnStaffCostsPerYearChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ZeroModel", "FK_NormalizedCalculations_Calculations", "Calculations")]
        public Calculations Calculation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Calculations>("ZeroModel.FK_NormalizedCalculations_Calculations", "Calculations").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Calculations>("ZeroModel.FK_NormalizedCalculations_Calculations", "Calculations").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Calculations> CalculationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Calculations>("ZeroModel.FK_NormalizedCalculations_Calculations", "Calculations");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Calculations>("ZeroModel.FK_NormalizedCalculations_Calculations", "Calculations", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ZeroModel", "FK_NormalizedCalculations_IpAddresses", "IpAddresses")]
        public IpAddresses IpAddress
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<IpAddresses>("ZeroModel.FK_NormalizedCalculations_IpAddresses", "IpAddresses").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<IpAddresses>("ZeroModel.FK_NormalizedCalculations_IpAddresses", "IpAddresses").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<IpAddresses> IpAddressReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<IpAddresses>("ZeroModel.FK_NormalizedCalculations_IpAddresses", "IpAddresses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<IpAddresses>("ZeroModel.FK_NormalizedCalculations_IpAddresses", "IpAddresses", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ZeroModel", Name="OnSiteEngagements")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OnSiteEngagements : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OnSiteEngagements object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        public static OnSiteEngagements CreateOnSiteEngagements(global::System.Guid id, global::System.DateTime date)
        {
            OnSiteEngagements onSiteEngagements = new OnSiteEngagements();
            onSiteEngagements.Id = id;
            onSiteEngagements.Date = date;
            return onSiteEngagements;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ForumUsers
        {
            get
            {
                return _ForumUsers;
            }
            set
            {
                OnForumUsersChanging(value);
                ReportPropertyChanging("ForumUsers");
                _ForumUsers = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ForumUsers");
                OnForumUsersChanged();
            }
        }
        private Nullable<global::System.Int32> _ForumUsers;
        partial void OnForumUsersChanging(Nullable<global::System.Int32> value);
        partial void OnForumUsersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NewsLetterSubscriptions
        {
            get
            {
                return _NewsLetterSubscriptions;
            }
            set
            {
                OnNewsLetterSubscriptionsChanging(value);
                ReportPropertyChanging("NewsLetterSubscriptions");
                _NewsLetterSubscriptions = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NewsLetterSubscriptions");
                OnNewsLetterSubscriptionsChanged();
            }
        }
        private Nullable<global::System.Int32> _NewsLetterSubscriptions;
        partial void OnNewsLetterSubscriptionsChanging(Nullable<global::System.Int32> value);
        partial void OnNewsLetterSubscriptionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Surveys
        {
            get
            {
                return _Surveys;
            }
            set
            {
                OnSurveysChanging(value);
                ReportPropertyChanging("Surveys");
                _Surveys = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Surveys");
                OnSurveysChanged();
            }
        }
        private Nullable<global::System.Int32> _Surveys;
        partial void OnSurveysChanging(Nullable<global::System.Int32> value);
        partial void OnSurveysChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Comments
        {
            get
            {
                return _Comments;
            }
            set
            {
                OnCommentsChanging(value);
                ReportPropertyChanging("Comments");
                _Comments = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Comments");
                OnCommentsChanged();
            }
        }
        private Nullable<global::System.Int32> _Comments;
        partial void OnCommentsChanging(Nullable<global::System.Int32> value);
        partial void OnCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CommentUsers
        {
            get
            {
                return _CommentUsers;
            }
            set
            {
                OnCommentUsersChanging(value);
                ReportPropertyChanging("CommentUsers");
                _CommentUsers = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CommentUsers");
                OnCommentUsersChanged();
            }
        }
        private Nullable<global::System.Int32> _CommentUsers;
        partial void OnCommentUsersChanging(Nullable<global::System.Int32> value);
        partial void OnCommentUsersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ForumTopics
        {
            get
            {
                return _ForumTopics;
            }
            set
            {
                OnForumTopicsChanging(value);
                ReportPropertyChanging("ForumTopics");
                _ForumTopics = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ForumTopics");
                OnForumTopicsChanged();
            }
        }
        private Nullable<global::System.Int32> _ForumTopics;
        partial void OnForumTopicsChanging(Nullable<global::System.Int32> value);
        partial void OnForumTopicsChanged();

        #endregion
    
    }

    #endregion
    
}
